services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - reviewzando-back/.env
  node_app:
    container_name: node_app
    build: ./reviewzando-back
    ports:
      - 1234:5000
    env_file:
      - reviewzando-back/.env
    depends_on:
      - db

volumes:
  postgres-volume: