services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - reviewzando-back/.env.development

  node:
    container_name: node
    build: ./reviewzando-back
    ports:
      - 5000:5000
    env_file:
      - reviewzando-back/.env.development
    depends_on:
      - postgres

  react:
    container_name: react
    build: ./reviewzando-front
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - react

volumes:
  postgres-volume:
  react-volume: