on:
  push:
    branches:
      - main
name: Build and Deploy on AWS
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          directory: reviewzando-back
          file_name: .env.development
          fail_on_empty: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
          envkey_VITE_TMDB_TOKEN: ${{secrets.VITE_TMDB_TOKEN}}
          directory: reviewzando-front
          file_name: .env
          fail_on_empty: true
      - name: Run docker compose down
        run: docker compose down -v # Não apague os volumes, senão o banco de dados de produção vai ser limpo.
      - name: Delete React docker volume
        run: if docker volume ls --quiet --filter name=Reviewzando_react-volume | grep -q .; then docker volume rm Reviewzando_react-volume; fi
      - name: Run docker compose up
        run: docker compose up --build -d
